apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 4  # Number of containers (replicas) you want to run
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: natour-app:v1  # Corrected image name
        ports:
        - containerPort: 3000  # Port inside the container
        resources:
          requests:
            memory: "256Mi"  # Memory requested by the container
            cpu: "250m"      # CPU requested by the container
          limits:
            memory: "512Mi"  # Maximum memory the container can use
            cpu: "500m"      # Maximum CPU the container can use
