apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  selector:
    app: node-app  # Make sure this matches the label in your Deployment file
  ports:
    - protocol: TCP
      port: 80       # Expose service on port 80
      targetPort: 3000 # Internal port inside the container
  type: ClusterIP
